---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectService
metadata:
  name: compute-engine-api
spec:
  providerConfigRef:
    name: admin
  forProvider:
    disableDependentServices: false
    service: compute.googleapis.com

---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectService
metadata:
  name: kubernetes-engine-api
spec:
  providerConfigRef:
    name: admin
  forProvider:
    disableDependentServices: false
    service: container.googleapis.com
