apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: admin
  namespace: crossplane-system
spec:
  projectID: magma-foster-devops
  credentials:
    source: Secret
    secretRef:
      key: credentials
      name: gcp-default
      namespace: crossplane-system
